# Generated by Django 4.1.7 on 2023-03-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loan_remove_user_created_on_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_to',
            new_name='loanee_full_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
