# Generated by Django 4.1.7 on 2023-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_loan_notify_loanee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='notify_loanee',
            field=models.BooleanField(default=False),
        ),
    ]
