# Generated by Django 4.1.7 on 2023-03-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_loan_notify_loanee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
