# Generated by Django 4.1.7 on 2023-03-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_loan_lender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='from_to',
            new_name='from_date',
        ),
    ]
