# Generated by Django 4.1.7 on 2023-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_from_to_loan_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
    ]
