# Generated by Django 4.1.7 on 2023-03-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_loan_loan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
    ]
